manual_may_ranks = {
 'nightsifyy': 'A',
 '1herocs': 'A',
 'caspy': 'A',
 'cjpriku': 'G',
 'clide1d': 'A',
 'colbzz': 'C',
 'dellzorfn': 'B',
 'frownnn': 'A',
 'gdpink': 'A',
 'herovit': 'B',
 'hydrexcs': 'S',
 'ipleadthe5cs': 'A',
 'isopandaman': 'B',
 'kaboosecs': 'S',
 'kelxdd': 'G',
 'landmaz': 'A',
 'masamxne': 'A',
 'mickslammit': 'G',
 'samanthaeg': 'B',
 'tenz': 'S',
 'theia': 'A',
 'tylercheetah': 'B',
 'wholewheatpete': 'A',
 'voltz420': 'C',
 'westcentralzz': 'C',
 'lirimmz': 'B',
 'brine_tv': 'C',
 'crossbar18': 'D',
 'heyitsboz': 'B',
 'a3har': 'B',
 'swazired': 'B',
 'br3ac': 'D',
 'adept_dave': 'B',
 'codsky': 'B',
 'itzace_gg': 'B',
 'dicezzz': 'B',
 'kingbonoboqc': 'B',
 'storfisk': 'C',
 'cok4in': 'B',
 'kimatarokisharo': 'C',
 'r3nch': 'C',
 'iserac': 'C',
 '1mountainog': 'A',
 '1sparx': 'B',
 '2bamboozled': 'B',
 'alejo98vs': 'A',
 'amnesia_cs': 'B',
 'axylus': 'A',
 'benzjamin': 'B',
 'bighurtz': 'D',
 'blunt_af': 'B',
 'bo0mie': 'B',
 'bot_sh4rk': 'B',
 'bratty': 'B',
 'caspy': 'A',
 'chill3k': 'C',
 'chimu90': 'C',
 'cilantro_live': 'B',
 'colbzz': 'C',
 'concuring': 'A',
 'crushingit79': 'B',
 'cryptt': 'B',
 'da_ft': 'B',
 'dellzorfn': 'B',
 'dire_cs': 'A',
 'doctormonsta': 'C',
 'drhippo': 'A',
 'dropdeadlexi': 'C',
 'drrtysal': 'C',
 'frownnn': 'A',
 'gajokerl': 'B',
 'goofplays': 'A',
 'hotsaucek2': 'B',
 'hunt__tv': 'B',
 'immenson': 'C',
 'imskizzy': 'B',
 'isopandaman': 'B',
 'itrxgic': 'C',
 'its_slim_': 'B',
 'itsbunch': 'B',
 'jackpot_usc': 'B',
 'jsetv': 'B',
 'kraytosthegod': 'A',
 'lilgrizz818': 'B',
 'lordnm': 'D',
 'mad3sto': 'B',
 'masonhtv': 'B',
 'mayorsayso': 'A',
 'modernkeyboard': 'D',
 'nerd0cs': 'B',
 'nick_thacker': 'A',
 'omgkam': 'C',
 'oogyl': 'B',
 'oriontaker': 'B',
 'pandacchaos': 'C',
 'passionite': 'B',
 'pattylovesyou': 'B',
 'roguexlimitz': 'D',
 'samanthaeg': 'B',
 'slight___': 'A',
 'smithninjas': 'C',
 'smoakland22': 'C',
 'sw_i_ms': 'B',
 'synge': 'B',
 'syzba': 'A',
 'the_doobie': 'B',
 'thepockypanduh': 'C',
 'tmay': 'B',
 'to3tagz': 'C',
 'ttvnyko': 'C',
 'tuulio': 'B',
 'tylercheetah': 'B',
 'very_classic': 'A',
 'vizzuaal': 'B',
 'vprex': 'B',
 'wholewheatpete': 'A',
 'xmalsz': 'B',
 'xxslayerrulesxx': 'C',
 'yatoyogurt': 'A',
 'zan3rg': 'C',
 'zealyth_': 'D',
 'zigster': 'C',
 'zijuu': 'B',
'piktorial' : 'A',
'realsicko_tv' : 'A',
'red_cyrex' : 'A',
'motm' : 'S',
'lenoncsgo' : 'G' ,
'hello_kaykay' : 'A',
'k3vin_csgo' : 'A',
'retroxox' : 'A',
'minusscs' :  'G',
'malbsmdsaiyajin' : 'G',
'lexcs' : 'G',
'conankun' : 'G',
'hated2k' : 'A',
'inseaniac_tv' : 'G',
'sh0ts' : 'A',
'dooran' : 'A',
'draxido' : 'A',
'krappydaklownjunior': 'A',
'natani_k': 'D',
'animegorls': 'B',
'abcdroid': 'C',
'joshinthebox169': 'A',
'reekris87': 'C',
'deejayfu': 'D',
'runawaychickenx': 'C',
'manzkid': 'B',
'farthammer1sg': 'B',
'n1copz': 'A',
'scorchyybc': 'B',
'josh_ortega': 'C',
'feralcod': 'C',
'fruxc': 'C',
'khemust': 'A',
'spcfoxtv': 'A',
'whitetehshadow': 'B' ,
'allingaming23': 'C',
'jas_cs': 'B',
'verzar6': 'B',
'kirshier': 'B',
'lazy_bum_': 'D' ,
'j9shtv': 'C',
'johnngavinn': 'B',
'josh_swan21': 'C',
'tv_deka': 'A',
'parfilo': 'B',
'zenixxcs': 'B',
'buddahkb': 'B',
'xanxiwnl': 'B',
'nitsua_tv': 'B',
'funies': 'B',
'mr_worthy': 'B',
'mattcdoeyt': 'C',
'thinkkfirst': 'B',
'birdman2642': 'D',
'swifttt_tv': 'C',
'glyyphh': 'B',
'andrhw': 'C',
'genesis_j': 'C',
'1stillmatic': 'B',
'hazardouslive': 'A',
'blairski7': 'A',
 'noxio': 'A',
'ashen_cs': 'A',
'imjynxlive': 'A',
'toyr34': 'S',
'aleksandarhz': 'G',
'kermeytheefrog': 'A',
'sharkie_tv': 'G',
'jmaldocs': 'A',
'las_cs': 'A',
'jewkcs': 'A',
'blakerscs': 'A',
'zaddynguyens': 'A',
'nzer0name': 'A',
'beastbox': 'A',
'lolatyourswag': 'A',
'mfxolddie': 'B' ,
'chqrlslol': 'C' ,
'plutomonium': 'B' ,
'physifyee': 'B' ,
'xtr_nbf': 'B' ,
'tannersorensen': 'B' ,
'alexastro': 'C' ,
'katernum': 'C' ,
'meagan': 'C' ,
'oomoomanoo': 'B' ,
'ec0nica': 'D' ,
'dabestchicken': 'D' ,
'phightme': 'A' ,
'yayooo_tv': 'B' ,
'daseegs': 'D' ,
'tors0_': 'A',
'exc1x': 'B' ,
'persian_tv': 'C' ,
'arzee_cs': 'A' ,
'fakeem': 'B' ,
'snoob_': 'B' ,
'hayon_tv': 'A' ,
'doubleapple': 'B' ,
'zephe': 'B' ,
'lumaaz': 'B' ,
'vzohhck': 'B',
'moroncs': 'A',
'slayerhz': 'A',
'palombatv': 'C',
'moechilla': 'A',
'c0nfusiontv': 'A',
'grxpecs': 'A',
'hellzaoocsgo': 'A',
'hammerna': 'A',
'deadhuntar': 'A',
'ehhspartan': 'A',
'therealflixxy': 'A',
'nicholaspcs': 'A',
'traviskun_': 'B',
'intry': 'A',
'1mannym': 'A',
'zanderd': 'G',
'alert_tv': 'A',
'fenomm': 'G',
'robbyo': 'A',
'cuz1h': 'A',
'crimgame': 'C' ,
'vitobad': 'D' ,
'sotz02': 'D' ,
'msxshots': 'B' ,
'tyler_a_lot': 'C' ,
'jethro_sb': 'C' ,
'tflug': 'B' ,
'nutty_live': 'B' ,
'blique_': 'B' ,
'maskk_tv': 'B',
'theanonymousrory': 'D' ,
'paukbhop': 'C' ,
'professorbeetus': 'D' ,
'chaddypz': 'B',
'realxsg': 'C' ,
'zan0theman0': 'D' ,
'itaroo_bot': 'D' ,
'suplexfps': 'A' ,
'ethxnnnn': 'A' ,
'polaroidnx': 'C' ,
'proteustv': 'B' ,
'daemgg': 'B' ,
'nicxcs': 'B' ,
'hokku': 'B' ,
'xelas_': 'B' ,
'dakzrp': 'B' ,
'shostak': 'C' ,
'daedus': 'C' ,
'rectum_spectrum': 'A',
'scem': 'B' ,
'flippybitsgg': 'D' ,
'humbabeast': 'A' ,
'bunnyisbad': 'A' ,
'mockcs': 'A' ,
'sushizcs': 'C',
'moeseftv': 'B' ,
'xajs': 'B' ,
'namhel_cs': 'D' ,
'mala': 'A'
}